version: '3.8'

services:
  frontend:
    image: 2.3/frontend
    build: ./frontend
    ports:
      - 5001:5001
  backend:
    image: 2.3/backend
    build: ./backend
    ports:
      - 8080:8080
  redis:
    image: library/redis:7.2.3-alpine
    build: .
    
      
